const icons = {
    addImage: require('./add-image.png'),
    add: require('./add.png'),
    back: require('./back.png'),
    categoryActive: require('./category-active.png'),
    category: require('./category.png'),
    comment: require('./comment.png'),
    homeActive: require('./home-active.png'),
    home: require('./home.png'),
    menu: require('./menu.png'),
    notificationActive: require('./notification-active.png'),
    notificationStatus: require('./notification-status.png'),
    notification: require('./notification.png'),
    optionHorizontal: require('./option-horizontal.png'),
    optionVertical: require('./option-vertical.png'),
    popularActive: require('./popular-active.png'),
    popular: require('./popular.png'),
    search: require('./search.png'),
    userActive: require('./user-active.png'),
    user: require('./user.png'),
    voteActive: require('./vote-active.png'),
    vote: require('./vote.png'),
};

export default icons;
